### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [powturbo/TurboRLE#1]
I would like to point out that an identifier like "[`_x__`](https://github.com/powturbo/TurboRLE/blob/dacac6fa40490dcc1c7f0c6bf6375cb71478d945/trle_.h#L46)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by powturbo** [comment]
thanks for your note. I've now adjusted TurboRLE

**Comment by elfring** [comment]
Thanks for [your improvement of affected identifiers](https://github.com/powturbo/TurboRLE/commit/f3612cf3efcbfac12648f0b0d0df6882f80ca600#diff-59280468f94df641be4944c7d2c4ba84L30 "Deletion of some underscores").
