### ISSUE TITLE
Improve const-correctness

### ISSUE THREAD

**Issue by elfring** [powturbo/TurboRLE#2]
I suggest to add the key word "const" to the type specifiers for parameters like "in" (function "[_srlec8](https://github.com/powturbo/TurboRLE/blob/c0fe7fa4d23d9e360db6c0ac6028f0d9f4b60b07/trle.h#L31 "Update candidate")").
Would you like to apply the advices from [an article](https://en.wikipedia.org/w/index.php?title=Const_%28computer_programming%29#Consequences "const-correctness") to more places in your source files?

**Comment by powturbo** [comment]
thanks for your note. I've now adjusted TurboRLE

**Comment by elfring** [comment]
Thanks for [your improvement of parameter properties](https://github.com/powturbo/TurboRLE/commit/f1394c35c5ea07ceb7caecf05eb9d34bcacf66b7#diff-51ffd463ff9ce48787e897f7ad67644eL31 "const-correctness").
