### ISSUE TITLE
Is there any detail usage for TurboRLE?

### ISSUE THREAD

**Issue by zhaochenyou** [powturbo/TurboRLE#3]
I'm a new guy for TurboRLE, I know something about Run Length Encoding, and I found TurboRLE in Github.
I download the src code and make it with gcc. 

My question is there any detail usage for TurboRLE?
Is the only function of TurboRLE is "trle.exe filename" ?
Can I get a compressed file by trle.exe ? Such as, I have a file "foo.txt", how can I use trle.exe to compress this "foo.txt" to "foo2.txt" ?

I didn't see any further guide or usage.

**Comment by powturbo** [comment]
I'll add some usage instructions in the readme, but you can also look at the benchmark program "trle".

usage is very simple : 

char uncompressed[N], compressed[N+64];
unsigned uncompressed_length = N;
unsigned compressed_length = trlec(uncompressed, uncompressed_length, compressed);
&
result =  trled(compressed, compressed_length, uncompressed, uncompressed_length);

trle.exe" is only a benchmark program for testing. There is no compressed output file.

**Comment by zhaochenyou** [comment]
Thanks, I understand, I can use TurboRLE to create my own compress application.
